### ISSUE TITLE
Unable to resolve symbol: multi-sample-trigger in this context

### ISSUE THREAD

**Issue by seabre** [josephwilk/mud#1]
When I run `(use '[mud.core])` in cider or plain old `lein repl`, Overtone loads, but then I immediately get:

```
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: multi-sample-trigger in this context, compiling:(mud/core.clj:215:6)
             java.lang.RuntimeException: Unable to resolve symbol: multi-sample-trigger in this context
```

I can't find `multi-sample-trigger` in MUD anywhere. 

My `project.clj` looks like:

``` clojure
(defproject overtone-live "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [overtone "0.9.1"]
                 [mud "0.1.0-SNAPSHOT"]])
```

**Comment by mattrei** [comment]
Hi,

yes had the same problem. The MUD Jar posted on clojars contains this multi-sample-trigger definition however it throws that error. Joseph got rid of it so you can't find it in the actual source.

So quick fix is, you delete your local mud libary in ~/.m2/repository/mud and clone this repo and do a lein install . 
Until Joseph updated the jar in the clojars repo.

Have fun!

**Comment by josephwilk** [comment]
I've pushed a new version which should have no more horrible `multi-sample-trigger`.
Sorry it took me a while to respond. I seem to completely fail at Github notifications.

Let me know if you have any other problems.

Thanks
